# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55199db782c0fb7343e436bd4c1fe4350a1cff5f38b7f139c23eb235e7c8f38cc73e8b61ad62502e2511ecc88452883e467164ee77d101b927900458925bbdd7

test:
  secret_key_base: 33e2961ffde34937b5e83d707bde3ebb0b02d8fe1731f6cf3493ef862c3b7d230897eaf7a666ba890feac9ecd7d75a1b6a962d6206dcb8e9ed6b5014a73f59cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
